### ISSUE TITLE
SpriteMeshes With Bones Binded Breaks SkinManager

### ISSUE THREAD

**Issue by MahdiMahzouni** [SergioAA97/AnimaSkin#1]
Binding Bones To SpriteMeshes Breaks The SkinManager Script And The Switched Skin Meshes Is disoriented any workaround ?

**Comment by lskuamoto** [comment]
Hi,
The only way that I could make the AnimaSkin work with bones was to bind the bones to the spritemeshes of the new skin.
I've followed the tutorial provided by Sergio on another video (https://www.youtube.com/watch?v=dI4u5Fsxebw).

**Comment by SergioAA97** [comment]
The bones will have to bound to the SpriteMeshes before using them with AnimaSkin. This is an issue with Anima2D and not with AnimaSkin.

I will close the issue as @lskuamoto provided an answer.
